#!/usr/bin/zsh -x
cd
if [[ ! -d vimified ]]
then
  git clone --recursive git@github.com:riannucci/vimified.git
fi
if [[ ! -d .oh-my-zsh ]]
then
  curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
fi
( mkdir -p .oh-my-zsh/custom/plugins &&
  cd .oh-my-zsh/custom/plugins &&
  git clone git://github.com/zsh-users/zsh-syntax-highlighting.git )

ln -sf vimified/ .config/nvim
ln -sf vimified/xmodmap .xmodmap
ln -sf vimified/ackrc .ackrc
ln -sf vimified/gitconfig .gitconfig

vim +PlugInstall +qa

ex .zshrc <<EOH
0
/^plugins
if line('.') == 1
  q
endif
c
source ~/vimified/zshrc.plugins
.
$
a
source ~/vimified/zshrc.extra
.
wq
EOH

