#!/usr/bin/zsh -x
cd
if [[ ! -d .config/nvim ]]
then
  mkdir .config || true
  git clone --recursive git@github.com:riannucci/vimified.git .config/nvim
fi
if [[ ! -d .oh-my-zsh ]]
then
  curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
  ( mkdir -p .oh-my-zsh/custom/plugins &&
    cd .oh-my-zsh/custom/plugins &&
    git clone git://github.com/zsh-users/zsh-syntax-highlighting.git )
fi

ln -sf .config/nvim/rando_dotfiles/xmodmap .xmodmap
ln -sf .config/nvim/rando_dotfiles/ackrc .ackrc
ln -sf .config/nvim/rando_dotfiles/gitconfig .gitconfig

vim +PlugInstall +qa

ex .zshrc <<EOH
0
/^plugins
if line('.') == 1
  q
endif
c
source ~/.config/nvim/rando_dotfiles/zshrc.plugins
.
$
a
source ~/.config/nvim/rando_dotfiles/zshrc.extra
.
wq
EOH

