[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
vi_mode_style = "Beam"

[font]
size = 16.0

[font.bold]
family = "DejaVu Sans Mono for Powerline"
style = "Bold"

[font.bold_italic]
family = "DejaVu Sans Mono for Powerline"
style = "Bold Oblique"

[font.italic]
family = "DejaVu Sans Mono for Powerline"
style = "Oblique"

[font.normal]
family = "DejaVu Sans Mono for Powerline"
style = "Book"

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/login"
args = ["-fp", "iannucci"]
